name: Build ViiCovers binaries

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install tkinter
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        pip install pyinstaller Pillow
        
    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Build with PyInstaller
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: ViiCovers.spec

    - name: Pack binary + data into tgz
      run: |
        tar -czvf ViiCovers_linux.tgz -C dist ViiCovers
          
    - name: Upload zipped bundle
      uses: actions/upload-artifact@v4
      with:
        name: ViiCovers-linux-bundle
        path: ViiCovers_linux.tgz
        
  build-windows:
    runs-on: windows-latest
    name: Build on Windows

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Dopasuj do wersji, której używasz

    - name: Install Poetry
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
      shell: powershell

    - name: Add Poetry to PATH
      run: echo "$env:USERPROFILE\AppData\Roaming\Python\Scripts" >> $env:GITHUB_PATH
      shell: powershell

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
        pip install pillow==11.3.0
      shell: powershell

    - name: Build with PyInstaller
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: ViiCovers.spec

    - name: Pack exe + data into zip
      run: |
        Compress-Archive -Path dist\ViiCovers -DestinationPath ViiCovers_windows.zip
      shell: powershell
      
    - name: Upload zipped bundle
      uses: actions/upload-artifact@v4
      with:
        name: ViiCovers-windows-bundle
        path: ViiCovers_windows.zip
